### ISSUE TITLE
document_user tablosu

### ISSUE THREAD

**Issue by mrtrca** [murat-cileli/papernic#11]
Merhaba,
Kurulumu tamamladım çalışıyor ancak doküman ekleme yaptığım zaman,

> An exception occurred while executing 'DELETE FROM document_user WHERE document_id = ?' with params ["7"]:

hatasını alıyorum,
document_user tablosu yok sanırım ancak SQL  çıktısında da göremedim bu tabloyu,

acaba SQL dosyası güncelmi?

İyi çalışmalar,

**Comment by murat-cileli** [comment]
@mrtrca Merhaba, yeni eklenen tabloyu SQL dosyasında güncellememişiz. Şimdilik aşağıdaki SQL dizisini çalıştırarak sorunu çözebilirsiniz.

`
CREATE TABLE `document_user` (
  `id` int(11) NOT NULL,
  `document_id` int(11) NOT NULL,
  `user_id` int(11) NOT NULL,
  `from_user_id` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;


ALTER TABLE `document_user`
  ADD PRIMARY KEY (`id`);

ALTER TABLE `document_user`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;

`

**Comment by mrtrca** [comment]
Teşekkür ederim.
Emeğinize sağlık.
